services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 5173:5173
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./backend/src:/app/src

volumes:
  backend_cache:
    driver: local