services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:80
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile.prod
