FROM maven:3.9.9-amazoncorretto-24 AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B && \
    apt-get install -y libnss3\
    libnspr4\
    libdbus-1-3\
    libatk1.0-0\
    libatk-bridge2.0-0\
    libatspi2.0-0\
    libxcomposite1\
    libxdamage1\
    libxfixes3\
    libgbm1\
    libxkbcommon0
COPY src ./src
RUN mvn package -DskipTests

FROM eclipse-temurin:24-jre
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]