FROM maven:3.9.9-amazoncorretto-24
WORKDIR /app
COPY pom.xml .
COPY src ./src

EXPOSE 8080

RUN mvn dependency:go-offline -B

CMD ["mvn", "spring-boot:run"]
#CMD ["mvn", "exec:java", "-e", "-D", "exec.mainClass=com.microsoft.playwright.CLI", "-D", "exec.args=install-deps"]
# WORKDIR /app

# COPY pom.xml .
# RUN mvn dependency:go-offline -B

# COPY src ./src

# RUN mvn package -DskipTests

# FROM selenium/standalone-chrome:latest

# COPY --from=0 /app/target/*.jar /app.jar

# CMD ["java", "-jar", "/app.jar"]